TRANSPARENT_BLOCKS = 0
WATER_BLOCKS = 12

# every block has a non-unique ID that it uses to decide its color on a map, here are those colors represented in decimal RGB
# there's an algorithm that can take the base color and compute the others but, whatever it's easier to hardcode. And probably faster, too
COLORS = {
    0: (
        (0, 0, 0),
        (0, 0, 0),
        (0, 0, 0),
        (0, 0, 0),
    ),

    1: (
        (89, 125, 39),
        (109, 153, 48),
        (127, 178, 56),
        (67, 94, 29),
    ),

    2: (
        (174, 164, 115),
        (213, 201, 140),
        (247, 233, 163),
        (130, 123, 86),
    ),

    3: (
        (140, 140, 140),
        (171, 171, 171),
        (199, 199, 199),
        (105, 105, 105),
    ),

    4: (
        (180, 0, 0),
        (220, 0, 0),
        (255, 0, 0),
        (135, 0, 0),
    ),

    5: (
        (112, 112, 180),
        (138, 138, 220),
        (160, 160, 255),
        (84, 84, 135),
    ),

    6: (
        (117, 117, 117),
        (144, 144, 144),
        (167, 167, 167),
        (88, 88, 88),
    ),

    7: (
        (0, 87, 0),
        (0, 106, 0),
        (0, 124, 0),
        (0, 65, 0),
    ),

    8: (
        (180, 180, 180),
        (220, 220, 220),
        (255, 255, 255),
        (135, 135, 135),
    ),

    9: (
        (115, 118, 129),
        (141, 144, 158),
        (164, 168, 184),
        (86, 88, 97),
    ),

    10: (
        (106, 76, 54),
        (130, 94, 66),
        (151, 109, 77),
        (79, 57, 40),
    ),

    11: (
        (79, 79, 79),
        (96, 96, 96),
        (112, 112, 112),
        (59, 59, 59),
    ),

    12: (
        (45, 45, 180),
        (55, 55, 220),
        (64, 64, 255),
        (33, 33, 135),
    ),

    13: (
        (100, 84, 50),
        (123, 102, 62),
        (143, 119, 72),
        (75, 63, 38),
    ),

    14: (
        (180, 177, 172),
        (220, 217, 211),
        (255, 252, 245),
        (135, 133, 129),
    ),

    15: (
        (152, 89, 36),
        (186, 109, 44),
        (216, 127, 51),
        (114, 67, 27),
    ),

    16: (
        (125, 53, 152),
        (153, 65, 186),
        (178, 76, 216),
        (94, 40, 114),
    ),

    17: (
        (72, 108, 152),
        (88, 132, 186),
        (102, 153, 216),
        (54, 81, 114),
    ),

    18: (
        (161, 161, 36),
        (197, 197, 44),
        (229, 229, 51),
        (121, 121, 27),
    ),

    19: (
        (89, 144, 17),
        (109, 176, 21),
        (127, 204, 25),
        (67, 108, 13),
    ),

    20: (
        (170, 89, 116),
        (208, 109, 142),
        (242, 127, 165),
        (128, 67, 87),
    ),

    21: (
        (53, 53, 53),
        (65, 65, 65),
        (76, 76, 76),
        (40, 40, 40),
    ),

    22: (
        (108, 108, 108),
        (132, 132, 132),
        (153, 153, 153),
        (81, 81, 81),
    ),

    23: (
        (53, 89, 108),
        (65, 109, 132),
        (76, 127, 153),
        (40, 67, 81),
    ),

    24: (
        (89, 44, 125),
        (109, 54, 153),
        (127, 63, 178),
        (67, 33, 94),
    ),

    25: (
        (36, 53, 125),
        (44, 65, 153),
        (51, 76, 178),
        (27, 40, 94),
    ),

    26: (
        (72, 53, 36),
        (88, 65, 44),
        (102, 76, 51),
        (54, 40, 27),
    ),

    27: (
        (72, 89, 36),
        (88, 109, 44),
        (102, 127, 51),
        (54, 67, 27),
    ),

    28: (
        (108, 36, 36),
        (132, 44, 44),
        (153, 51, 51),
        (81, 27, 27),
    ),

    29: (
        (17, 17, 17),
        (21, 21, 21),
        (25, 25, 25),
        (13, 13, 13),
    ),

    30: (
        (176, 168, 54),
        (215, 205, 66),
        (250, 238, 77),
        (132, 126, 40),
    ),

    31: (
        (64, 154, 150),
        (79, 188, 183),
        (92, 219, 213),
        (48, 115, 112),
    ),

    32: (
        (52, 90, 180),
        (63, 110, 220),
        (74, 128, 255),
        (39, 67, 135),
    ),

    33: (
        (0, 153, 40),
        (0, 187, 50),
        (0, 217, 58),
        (0, 114, 30),
    ),

    34: (
        (91, 60, 34),
        (111, 74, 42),
        (129, 86, 49),
        (68, 45, 25),
    ),

    35: (
        (79, 1, 0),
        (96, 1, 0),
        (112, 2, 0),
        (59, 1, 0),
    ),

    36: (
        (147, 124, 113),
        (180, 152, 138),
        (209, 177, 161),
        (110, 93, 85),
    ),

    37: (
        (112, 57, 25),
        (137, 70, 31),
        (159, 82, 36),
        (84, 43, 19),
    ),

    38: (
        (105, 61, 76),
        (128, 75, 93),
        (149, 87, 108),
        (78, 46, 57),
    ),

    39: (
        (79, 76, 97),
        (96, 93, 119),
        (112, 108, 138),
        (59, 57, 73),
    ),

    40: (
        (131, 93, 25),
        (160, 114, 31),
        (186, 133, 36),
        (98, 70, 19),
    ),

    41: (
        (72, 82, 37),
        (88, 100, 45),
        (103, 117, 53),
        (54, 62, 28),
    ),

    42: (
        (112, 54, 55),
        (138, 66, 67),
        (160, 77, 78),
        (84, 40, 41),
    ),

    43: (
        (40, 28, 24),
        (49, 35, 30),
        (57, 41, 35),
        (30, 21, 18),
    ),

    44: (
        (95, 75, 69),
        (116, 92, 84),
        (135, 107, 98),
        (71, 56, 51),
    ),

    45: (
        (61, 64, 64),
        (75, 79, 79),
        (87, 92, 92),
        (46, 48, 48),
    ),

    46: (
        (86, 51, 62),
        (105, 63, 75),
        (122, 73, 88),
        (64, 38, 46),
    ),

    47: (
        (53, 43, 64),
        (65, 53, 79),
        (76, 62, 92),
        (40, 32, 48),
    ),

    48: (
        (53, 35, 24),
        (65, 43, 30),
        (76, 50, 35),
        (40, 26, 18),
    ),

    49: (
        (53, 57, 29),
        (65, 70, 36),
        (76, 82, 42),
        (40, 43, 22),
    ),

    50: (
        (100, 42, 32),
        (122, 51, 39),
        (142, 60, 46),
        (75, 31, 24),
    ),

    51: (
        (26, 15, 11),
        (31, 18, 13),
        (37, 22, 16),
        (19, 11, 8),
    ),

    52: (
        (133, 33, 34),
        (163, 41, 42),
        (189, 48, 49),
        (100, 25, 26),
    ),

    53: (
        (104, 44, 68),
        (127, 54, 83),
        (148, 63, 97),
        (78, 33, 51),
    ),

    54: (
        (64, 17, 20),
        (79, 21, 25),
        (92, 25, 29),
        (48, 13, 15),
    ),

    55: (
        (15, 88, 94),
        (18, 108, 115),
        (22, 126, 134),
        (11, 66, 70),
    ),

    56: (
        (40, 100, 98),
        (50, 122, 120),
        (58, 142, 140),
        (30, 75, 73),
    ),

    57: (
        (60, 31, 43),
        (74, 37, 53),
        (86, 44, 62),
        (45, 23, 32),
    ),

    58: (
        (14, 127, 93),
        (17, 155, 114),
        (20, 180, 133),
        (10, 95, 70),
    ),

    59: (
        (70, 70, 70),
        (86, 86, 86),
        (100, 100, 100),
        (52, 52, 52),
    ),

    60: (
        (152, 123, 103),
        (186, 150, 126),
        (216, 175, 147),
        (114, 93, 78),
    ),

    61: (
        (89, 117, 105),
        (109, 144, 129),
        (127, 167, 150),
        (67, 88, 79),
    ),
}

BLOCK_ID = {
    "minecraft:air": 0,
    "minecraft:void_air": 0,
    "minecraft:cave_air": 0,
    "minecraft:barrier": 0,
    "minecraft:cake": 0,
    "minecraft:cake_with_candle": 0,
    "minecraft:powered_rail": 0,
    "minecraft:detector_rail": 0,
    "minecraft:torch": 0,
    "minecraft:wall_torch": 0,
    "minecraft:redstone_torch": 0,
    "minecraft:redstone_wall_torch": 0,
    "minecraft:soul_torch": 0,
    "minecraft:soul_wall_torch": 0,
    "minecraft:redstone_wire": 0,
    "minecraft:ladder": 0,
    "minecraft:rail": 0,
    "minecraft:lever": 0,
    "minecraft:button": 0,
    "minecraft:oak_button": 0,
    "minecraft:spruce_button": 0,
    "minecraft:birch_button": 0,
    "minecraft:jungle_button": 0,
    "minecraft:acacia_button": 0,
    "minecraft:dark_oak_button": 0,
    "minecraft:mangrove_button": 0,
    "minecraft:cherry_button": 0,
    "minecraft:pale_oak_button": 0,
    "minecraft:bamboo_button": 0,
    "minecraft:crimson_button": 0,
    "minecraft:warped_button": 0,
    "minecraft:stone_button": 0,
    "minecraft:polished_blackstone_button": 0,
    "minecraft:repeater": 0,
    "minecraft:tripwire_hook": 0,
    "minecraft:tripwire": 0,
    "minecraft:flower_pot": 0,
    "minecraft:potted_plant": 0,
    "minecraft:flower_pot": 0,
    "minecraft:potted_oak_sapling": 0,
    "minecraft:potted_spruce_sapling": 0,
    "minecraft:potted_birch_sapling": 0,
    "minecraft:potted_jungle_sapling": 0,
    "minecraft:potted_acacia_sapling": 0,
    "minecraft:potted_dark_oak_sapling": 0,
    "minecraft:potted_mangrove_propagule": 0,
    "minecraft:potted_cherry_sapling": 0,
    "minecraft:potted_pale_oak_sapling": 0,
    "minecraft:potted_fern": 0,
    "minecraft:potted_dandelion": 0,
    "minecraft:potted_poppy": 0,
    "minecraft:potted_blue_orchid": 0,
    "minecraft:potted_allium": 0,
    "minecraft:potted_azure_bluet": 0,
    "minecraft:potted_red_tulip": 0,
    "minecraft:potted_orange_tulip": 0,
    "minecraft:potted_white_tulip": 0,
    "minecraft:potted_pink_tulip": 0,
    "minecraft:potted_oxeye_daisy": 0,
    "minecraft:potted_cornflower": 0,
    "minecraft:potted_lily_of_the_valley": 0,
    "minecraft:potted_wither_rose": 0,
    "minecraft:potted_torchflower": 0,
    "minecraft:potted_closed_eyeblossom": 0,
    "minecraft:potted_open_eyeblossom": 0,
    "minecraft:potted_red_mushroom": 0,
    "minecraft:potted_brown_mushroom": 0,
    "minecraft:potted_dead_bush": 0,
    "minecraft:potted_cactus": 0,
    "minecraft:potted_bamboo": 0,
    "minecraft:potted_azalea_bush": 0,
    "minecraft:potted_flowering_azalea_bush": 0,
    "minecraft:potted_crimson_fungus": 0,
    "minecraft:potted_warped_fungus": 0,
    "minecraft:potted_crimson_roots": 0,
    "minecraft:potted_warped_roots": 0,
    "minecraft:potted_oak_leaves": 0,
    "minecraft:potted_spruce_leaves": 0,
    "minecraft:potted_birch_leaves": 0,
    "minecraft:potted_jungle_leaves": 0,
    "minecraft:potted_acacia_leaves": 0,
    "minecraft:potted_dark_oak_leaves": 0,
    "minecraft:potted_mangrove_leaves": 0,
    "minecraft:potted_cherry_leaves": 0,
    "minecraft:potted_pale_oak_leaves": 0,
    "minecraft:skeleton_skull": 0,
    "minecraft:skeleton_wall_skull": 0,
    "minecraft:wither_skeleton_skull": 0,
    "minecraft:wither_skeleton_wall_skull": 0,
    "minecraft:zombie_head": 0,
    "minecraft:zombie_wall_head": 0,
    "minecraft:player_head": 0,
    "minecraft:player_wall_head": 0,
    "minecraft:creeper_head": 0,
    "minecraft:creeper_wall_head": 0,
    "minecraft:piglin_head": 0,
    "minecraft:piglin_wall_head": 0,
    "minecraft:dragon_head": 0,
    "minecraft:dragon_wall_head": 0,
    "minecraft:comparator": 0,
    "minecraft:activator_rail": 0,
    "minecraft:end_rod": 0,
    "minecraft:glass": 0,
    "minecraft:glass_pane": 0,
    "minecraft:nether_portal": 0,
    "minecraft:white_stained_glass_pane": 0,
    "minecraft:orange_stained_glass_pane": 0,
    "minecraft:magenta_stained_glass_pane": 0,
    "minecraft:light_blue_stained_glass_pane": 0,
    "minecraft:yellow_stained_glass_pane": 0,
    "minecraft:lime_stained_glass_pane": 0,
    "minecraft:pink_stained_glass_pane": 0,
    "minecraft:gray_stained_glass_pane": 0,
    "minecraft:light_gray_stained_glass_pane": 0,
    "minecraft:cyan_stained_glass_pane": 0,
    "minecraft:purple_stained_glass_pane": 0,
    "minecraft:blue_stained_glass_pane": 0,
    "minecraft:brown_stained_glass_pane": 0,
    "minecraft:green_stained_glass_pane": 0,
    "minecraft:red_stained_glass_pane": 0,
    "minecraft:black_stained_glass_pane": 0,
    "minecraft:structure_void": 0,
    "minecraft:iron_bars": 0,
    "minecraft:iron_chain": 0,
    "minecraft:light": 0,
    "minecraft:test_instance_block": 0,
    "minecraft:mangrove_propagule": 0,


    "minecraft:grass_block": 1,
    "minecraft:slime_block": 1,

    "minecraft:sand": 2,
    "minecraft:suspicious_sand": 2,
    "minecraft:birch_planks": 2,
    "minecraft:birch_log": 2,
    "minecraft:stripped_birch_log": 2,
    "minecraft:birch_wood": 2,
    "minecraft:stripped_birch_wood": 2,
    "minecraft:birch_sign": 2,
    "minecraft:birch_wall_sign": 2,
    "minecraft:birch_pressure_plate": 2,
    "minecraft:birch_trapdoor": 2,
    "minecraft:birch_stairs": 2,
    "minecraft:birch_slab": 2,
    "minecraft:birch_fence_gate": 2,
    "minecraft:birch_fence": 2,
    "minecraft:birch_door": 2,
    "minecraft:sandstone": 2,
    "minecraft:chiseled_sandstone": 2,
    "minecraft:cut_sandstone": 2,
    "minecraft:smooth_sandstone": 2,
    "minecraft:sandstone_slab": 2,
    "minecraft:cut_sandstone_slab": 2,
    "minecraft:smooth_sandstone_slab": 2,
    "minecraft:sandstone_stairs": 2,
    "minecraft:smooth_sandstone_stairs": 2,
    "minecraft:sandstone_wall": 2,
    "minecraft:glowstone": 2,
    "minecraft:end_stone": 2,
    "minecraft:end_stone_bricks": 2,
    "minecraft:end_stone_brick_slab": 2,
    "minecraft:end_stone_brick_stairs": 2,
    "minecraft:end_stone_brick_wall": 2,
    "minecraft:bone_block": 2,
    "minecraft:turtle_egg": 2,
    "minecraft:scaffolding": 2,
    "minecraft:candle": 2,
    "minecraft:ochre_froglight": 2,
    "minecraft:frogspawn": 2,

    "minecraft:cobweb": 3,
    "minecraft:mushroom_stem": 3,
    # only the heads of the beds should be ID 3 but whatever
    "minecraft:white_bed": 3,
    "minecraft:orange_bed": 3,
    "minecraft:magenta_bed": 3,
    "minecraft:light_blue_bed": 3,
    "minecraft:yellow_bed": 3,
    "minecraft:lime_bed": 3,
    "minecraft:pink_bed": 3,
    "minecraft:gray_bed": 3,
    "minecraft:light_gray_bed": 3,
    "minecraft:cyan_bed": 3,
    "minecraft:purple_bed": 3,
    "minecraft:blue_bed": 3,
    "minecraft:brown_bed": 3,
    "minecraft:green_bed": 3,
    "minecraft:red_bed": 3,
    "minecraft:black_bed": 3,
    "minecraft:white_candle": 3,

    "minecraft:lava": 4,
    "minecraft:tnt": 4,
    "minecraft:fire": 4,
    "minecraft:redstone_block": 4,

    "minecraft:ice": 5,
    "minecraft:frosted_ice": 5,
    "minecraft:packed_ice": 5,
    "minecraft:blue_ice": 5,

    "minecraft:iron_block": 6,
    "minecraft:iron_door": 6,
    "minecraft:brewing_stand": 6,
    "minecraft:heavy_weighted_pressure_plate": 6,
    "minecraft:iron_trapdoor": 6,
    "minecraft:lantern": 6,
    "minecraft:anvil": 6,
    "minecraft:chipped_anvil": 6,
    "minecraft:damaged_anvil": 6,
    "minecraft:grindstone": 6,
    "minecraft:lodestone": 6,
    "minecraft:heavy_core": 6,
    "minecraft:pale_oak_leaves": 6,
    "minecraft:pale_oak_sapling": 6,
    "minecraft:closed_eyeblossom": 6,

    "minecraft:oak_sapling": 7,
    "minecraft:spruce_sapling": 7,
    "minecraft:birch_sapling": 7,
    "minecraft:jungle_sapling": 7,
    "minecraft:acacia_sapling": 7,
    "minecraft:dark_oak_sapling": 7,
    "minecraft:dandelion": 7,
    "minecraft:poppy": 7,
    "minecraft:blue_orchid": 7,
    "minecraft:allium": 7,
    "minecraft:azure_bluet": 7,
    "minecraft:red_tulip": 7,
    "minecraft:orange_tulip": 7,
    "minecraft:white_tulip": 7,
    "minecraft:pink_tulip": 7,
    "minecraft:oxeye_daisy": 7,
    "minecraft:cornflower": 7,
    "minecraft:lily_of_the_valley": 7,
    "minecraft:wither_rose": 7,
    "minecraft:sunflower": 7,
    "minecraft:lilac": 7,
    "minecraft:rose_bush": 7,
    "minecraft:peony": 7,
    "minecraft:torchflower": 7,
    "minecraft:closed_eyeblossom": 7,
    "minecraft:open_eyeblossom": 7,
    "minecraft:pitcher_plant": 7,
    "minecraft:wheat": 7,
    "minecraft:sugar_cane": 7,
    "minecraft:pumpkin_stem": 7,
    "minecraft:attached_pumpkin_stem": 7,
    "minecraft:melon_stem": 7,
    "minecraft:attached_melon_stem": 7,
    "minecraft:carrots": 7,
    "minecraft:potatoes": 7,
    "minecraft:beetroots": 7,
    "minecraft:lily_pad": 7,
    "minecraft:cocoa": 7,
    "minecraft:sweet_berry_bush": 7,
    "minecraft:short_grass": 7,
    "minecraft:tall_grass": 7,
    "minecraft:fern": 7,
    "minecraft:large_fern": 7,
    "minecraft:vine": 7,
    "minecraft:weeping_vines": 7,
    "minecraft:weeping_vines_plant": 7,
    "minecraft:twisting_vines": 7,
    "minecraft:twisting_vines_plant": 7,
    "minecraft:oak_leaves": 7,
    "minecraft:spruce_leaves": 7,
    "minecraft:birch_leaves": 7,
    "minecraft:jungle_leaves": 7,
    "minecraft:acacia_leaves": 7,
    "minecraft:dark_oak_leaves": 7,
    "minecraft:azalea_leaves": 7,
    "minecraft:flowering_azalea_leaves": 7,
    "minecraft:mangrove_leaves": 7,
    "minecraft:cactus": 7,
    "minecraft:bamboo": 7,
    "minecraft:bamboo_shoot": 7,
    "minecraft:cave_vines": 7,
    "minecraft:cave_vines_plant": 7,
    "minecraft:spore_blossom": 7,
    "minecraft:azalea": 7,
    "minecraft:flowering_azalea": 7,
    "minecraft:big_dripleaf": 7,
    "minecraft:big_dripleaf_stem": 7,
    "minecraft:small_dripleaf": 7,
    "minecraft:pink_petals": 7,
    "minecraft:wildflowers": 7,
    "minecraft:bush": 7,
    "minecraft:torchflower_seeds": 7,

    "minecraft:snow": 8,
    "minecraft:snow_block": 8,
    "minecraft:white_wool": 8,
    "minecraft:white_stained_glass": 8,
    "minecraft:white_carpet": 8,
    "minecraft:white_shulker_box": 8,
    "minecraft:white_glazed_terracotta": 8,
    "minecraft:white_concrete": 8,
    "minecraft:white_concrete_powder": 8,
    "minecraft:powder_snow": 8,

    "minecraft:clay": 9,
    "minecraft:infested_stone": 9,
    "minecraft:infested_cobblestone": 9,
    "minecraft:infested_stone_bricks": 9,
    "minecraft:infested_mossy_stone_bricks": 9,
    "minecraft:infested_cracked_stone_bricks": 9,
    "minecraft:infested_chiseled_stone_bricks": 9,

    "minecraft:dirt": 10,
    "minecraft:coarse_dirt": 10,
    "minecraft:farmland": 10,
    "minecraft:dirt_path": 10,
    "minecraft:granite": 10,
    "minecraft:granite_slab": 10,
    "minecraft:granite_stairs": 10,
    "minecraft:granite_wall": 10,
    "minecraft:polished_granite": 10,
    "minecraft:polished_granite_slab": 10,
    "minecraft:polished_granite_stairs": 10,
    "minecraft:jungle_planks": 10,
    "minecraft:jungle_log": 10,
    "minecraft:stripped_jungle_log": 10,
    "minecraft:jungle_wood": 10,
    "minecraft:stripped_jungle_wood": 10,
    "minecraft:jungle_sign": 10,
    "minecraft:jungle_wall_sign": 10,
    "minecraft:jungle_pressure_plate": 10,
    "minecraft:jungle_trapdoor": 10,
    "minecraft:jungle_stairs": 10,
    "minecraft:jungle_slab": 10,
    "minecraft:jungle_fence_gate": 10,
    "minecraft:jungle_fence": 10,
    "minecraft:jungle_door": 10,
    "minecraft:jukebox": 10,
    "minecraft:brown_mushroom_block": 10,
    "minecraft:rooted_dirt": 10,
    "minecraft:hanging_roots": 10,
    "minecraft:packed_mud": 10,

    "minecraft:stone": 11,
    "minecraft:stone_slab": 11,
    "minecraft:stone_stairs": 11,
    "minecraft:andesite": 11,
    "minecraft:andesite_slab": 11,
    "minecraft:andesite_stairs": 11,
    "minecraft:andesite_wall": 11,
    "minecraft:polished_andesite": 11,
    "minecraft:polished_andesite_slab": 11,
    "minecraft:polished_andesite_stairs": 11,
    "minecraft:cobblestone": 11,
    "minecraft:cobblestone_slab": 11,
    "minecraft:cobblestone_stairs": 11,
    "minecraft:cobblestone_wall": 11,
    "minecraft:bedrock": 11,
    "minecraft:gold_ore": 11,
    "minecraft:iron_ore": 11,
    "minecraft:coal_ore": 11,
    "minecraft:lapis_ore": 11,
    "minecraft:dispenser": 11,
    "minecraft:mossy_cobblestone": 11,
    "minecraft:mossy_cobblestone_slab": 11,
    "minecraft:mossy_cobblestone_stairs": 11,
    "minecraft:mossy_cobblestone_wall": 11,
    "minecraft:spawner": 11,
    "minecraft:diamond_ore": 11,
    "minecraft:furnace": 11,
    "minecraft:stone_pressure_plate": 11,
    "minecraft:redstone_ore": 11,
    "minecraft:stone_bricks": 11,
    "minecraft:cracked_stone_bricks": 11,
    "minecraft:chiseled_stone_bricks": 11,
    "minecraft:mossy_stone_bricks": 11,
    "minecraft:stone_brick_slab": 11,
    "minecraft:cracked_stone_bricks": 11,
    "minecraft:mossy_stone_brick_slab": 11,
    "minecraft:stone_brick_stairs": 11,
    "minecraft:mossy_stone_brick_stairs": 11,
    "minecraft:stone_brick_wall": 11,
    "minecraft:mossy_stone_brick_wall": 11,
    "minecraft:emerald_ore": 11,
    "minecraft:ender_chest": 11,
    "minecraft:dropper": 11,
    "minecraft:smooth_stone": 11,
    "minecraft:smooth_stone_slab": 11,
    "minecraft:observer": 11,
    "minecraft:smoker": 11,
    "minecraft:blast_furnace": 11,
    "minecraft:stonecutter": 11,
    "minecraft:sticky_piston": 11,
    "minecraft:piston": 11,
    "minecraft:piston_head": 11,
    "minecraft:gravel": 11,
    "minecraft:suspicious_gravel": 11,
    "minecraft:acacia_log": 11,
    "minecraft:cauldron": 11,
    "minecraft:water_cauldron": 11,
    "minecraft:lava_cauldron": 11,
    "minecraft:powder_snow_cauldron": 11,
    "minecraft:hopper": 11,
    "minecraft:copper_ore": 11,
    "minecraft:crafter": 11,
    "minecraft:vault": 11,
    "minecraft:trial_spawner": 11,
    "minecraft:pale_oak_wood": 11,
    "minecraft:pale_oak_log": 11,
    "minecraft:heavy_core": 11,

    # waterlogged leaves should be included here, I can't be bothered though
    "minecraft:seagrass": 12,
    "minecraft:tall_seagrass": 12,
    "minecraft:water": 12,
    "minecraft:bubble_column": 12,
    "minecraft:kelp": 12,
    "minecraft:kelp_plant": 12,

    "minecraft:oak_planks": 13,
    "minecraft:oak_log": 13,
    "minecraft:stripped_oak_log": 13,
    "minecraft:oak_wood": 13,
    "minecraft:stripped_oak_wood": 13,
    "minecraft:oak_sign": 13,
    "minecraft:oak_wall_sign": 13,
    "minecraft:oak_door": 13,
    "minecraft:oak_pressure_plate": 13,
    "minecraft:oak_fence": 13,
    "minecraft:oak_trapdoor": 13,
    "minecraft:oak_fence_gate": 13,
    "minecraft:oak_slab": 13,
    "minecraft:oak_stairs": 13,
    "minecraft:note_block": 13,
    "minecraft:bookshelf": 13,
    "minecraft:chiseled_bookshelf": 13,
    "minecraft:chest": 13,
    "minecraft:crafting_table": 13,
    "minecraft:trapped_chest": 13,
    "minecraft:daylight_detector": 13,
    "minecraft:loom": 13,
    "minecraft:barrel": 13,
    "minecraft:cartography_table": 13,
    "minecraft:fletching_table": 13,
    "minecraft:lectern": 13,
    "minecraft:smithing_table": 13,
    "minecraft:composter": 13,
    "minecraft:bamboo_sapling": 13,
    "minecraft:dead_bush": 13,
    "minecraft:petrified_oak_slab": 13,
    "minecraft:beehive": 13,
    "minecraft:white_banner": 13,
    "minecraft:orange_banner": 13,
    "minecraft:magenta_banner": 13,
    "minecraft:light_blue_banner": 13,
    "minecraft:yellow_banner": 13,
    "minecraft:lime_banner": 13,
    "minecraft:pink_banner": 13,
    "minecraft:gray_banner": 13,
    "minecraft:light_gray_banner": 13,
    "minecraft:cyan_banner": 13,
    "minecraft:purple_banner": 13,
    "minecraft:blue_banner": 13,
    "minecraft:brown_banner": 13,
    "minecraft:green_banner": 13,
    "minecraft:red_banner": 13,
    "minecraft:black_banner": 13,
    "minecraft:white_wall_banner": 13,
    "minecraft:orange_wall_banner": 13,
    "minecraft:magenta_wall_banner": 13,
    "minecraft:light_blue_wall_banner": 13,
    "minecraft:yellow_wall_banner": 13,
    "minecraft:lime_wall_banner": 13,
    "minecraft:pink_wall_banner": 13,
    "minecraft:gray_wall_banner": 13,
    "minecraft:light_gray_wall_banner": 13,
    "minecraft:cyan_wall_banner": 13,
    "minecraft:purple_wall_banner": 13,
    "minecraft:blue_wall_banner": 13,
    "minecraft:brown_wall_banner": 13,
    "minecraft:green_wall_banner": 13,
    "minecraft:red_wall_banner": 13,
    "minecraft:black_wall_banner": 13,

    "minecraft:diorite": 14,
    "minecraft:diorite_stairs": 14,
    "minecraft:diorite_slab": 14,
    "minecraft:diorite_wall": 14,
    "minecraft:polished_diorite": 14,
    "minecraft:polished_diorite_stairs": 14,
    "minecraft:polished_diorite_slab": 14,
    "minecraft:birch_log": 14,
    "minecraft:quartz_block": 14,
    "minecraft:chiseled_quartz_block": 14,
    "minecraft:quartz_bricks": 14,
    "minecraft:quartz_pillar": 14,
    "minecraft:smooth_quartz": 14,
    "minecraft:quartz_slab": 14,
    "minecraft:smooth_quartz_slab": 14,
    "minecraft:quartz_stairs": 14,
    "minecraft:smooth_quartz_stairs": 14,
    "minecraft:sea_lantern": 14,
    "minecraft:target": 14,
    "minecraft:pale_oak_planks": 14,
    "minecraft:pale_oak_log": 14,
    "minecraft:stripped_pale_oak_log": 14,
    "minecraft:stripped_pale_oak_wood": 14,
    "minecraft:pale_oak_sign": 14,
    "minecraft:pale_oak_wall_sign": 14,
    "minecraft:pale_oak_pressure_plate": 14,
    "minecraft:pale_oak_trapdoor": 14,
    "minecraft:pale_oak_stairs": 14,
    "minecraft:pale_oak_slab": 14,
    "minecraft:pale_oak_fence_gate": 14,
    "minecraft:pale_oak_fence": 14,
    "minecraft:pale_oak_door": 14,

    "minecraft:acacia_planks": 15,
    "minecraft:acacia_log": 15,
    "minecraft:stripped_acacia_log": 15,
    "minecraft:stripped_acacia_wood": 15,
    "minecraft:acacia_sign": 15,
    "minecraft:acacia_wall_sign": 15,
    "minecraft:acacia_trapdoor": 15,
    "minecraft:acacia_slab": 15,
    "minecraft:acacia_stairs": 15,
    "minecraft:acacia_pressure_plate": 15,
    "minecraft:acacia_fence_gate": 15,
    "minecraft:acacia_fence": 15,
    "minecraft:acacia_door": 15,
    "minecraft:red_sand": 15,
    "minecraft:orange_wool": 15,
    "minecraft:orange_carpet": 15,
    "minecraft:orange_shulker_box": 15,
    "minecraft:orange_bed": 15,
    "minecraft:orange_stained_glass": 15,
    "minecraft:orange_glazed_terracotta": 15,
    "minecraft:orange_concrete": 15,
    "minecraft:orange_concrete_powder": 15,
    "minecraft:orange_candle": 15,
    "minecraft:pumpkin": 15,
    "minecraft:carved_pumpkin": 15,
    "minecraft:jack_o_lantern": 15,
    "minecraft:terracotta": 15,
    "minecraft:red_sandstone": 15,
    "minecraft:chiseled_red_sandstone": 15,
    "minecraft:cut_red_sandstone": 15,
    "minecraft:smooth_red_sandstone": 15,
    "minecraft:red_sandstone_stairs": 15,
    "minecraft:smooth_red_sandstone_stairs": 15,
    "minecraft:red_sandstone_slab": 15,
    "minecraft:cut_red_sandstone_slab": 15,
    "minecraft:smooth_red_sandstone_slab": 15,
    "minecraft:red_sandstone_wall": 15,
    "minecraft:honey_block": 15,
    "minecraft:honeycomb_block": 15,
    "minecraft:copper_block": 15,
    "minecraft:cut_copper": 15,
    "minecraft:cut_copper_stairs": 15,
    "minecraft:cut_copper_slab": 15,
    "minecraft:waxed_copper_block": 15,
    "minecraft:waxed_cut_copper": 15,
    "minecraft:waxed_cut_copper_stairs": 15,
    "minecraft:waxed_cut_copper_slab": 15,
    "minecraft:raw_copper_block": 15,
    "minecraft:creaking_heart": 15,
    "minecraft:open_eyeblossom": 15,
    "minecraft:waxed_copper_block": 15,
    "minecraft:waxed_cut_copper": 15,
    "minecraft:waxed_cut_copper_stairs": 15,
    "minecraft:waxed_cut_copper_slab": 15,
    "minecraft:lightning_rod": 15,
    "minecraft:waxed_lightning_rod": 15,

    "minecraft:magenta_wool": 16,
    "minecraft:magenta_carpet": 16,
    "minecraft:magenta_shulker_box": 16,
    "minecraft:magenta_bed": 16,
    "minecraft:magenta_stained_glass": 16,
    "minecraft:magenta_glazed_terracotta": 16,
    "minecraft:magenta_concrete": 16,
    "minecraft:magenta_concrete_powder": 16,
    "minecraft:magenta_candle": 16,
    "minecraft:purpur_block": 16,
    "minecraft:purpur_pillar": 16,
    "minecraft:purpur_slab": 16,
    "minecraft:purpur_stairs": 16,

    "minecraft:light_blue_wool": 17,
    "minecraft:light_blue_carpet": 17,
    "minecraft:light_blue_shulker_box": 17,
    "minecraft:light_blue_bed": 17,
    "minecraft:light_blue_stained_glass": 17,
    "minecraft:light_blue_glazed_terracotta": 17,
    "minecraft:light_blue_concrete": 17,
    "minecraft:light_blue_concrete_powder": 17,
    "minecraft:light_blue_candle": 17,
    "minecraft:soul_fire": 17,

    "minecraft:yellow_wool": 18,
    "minecraft:yellow_carpet": 18,
    "minecraft:yellow_shulker_box": 18,
    "minecraft:yellow_bed": 18,
    "minecraft:yellow_stained_glass": 18,
    "minecraft:yellow_glazed_terracotta": 18,
    "minecraft:yellow_concrete": 18,
    "minecraft:yellow_concrete_powder": 18,
    "minecraft:yellow_candle": 18,
    "minecraft:bamboo_planks": 18,
    "minecraft:stripped_bamboo": 18,
    "minecraft:bamboo_sign": 18,
    "minecraft:bamboo_wall_sign": 18,
    "minecraft:bamboo_door": 18,
    "minecraft:bamboo_pressure_plate": 18,
    "minecraft:bamboo_fence": 18,
    "minecraft:bamboo_trapdoor": 18,
    "minecraft:bamboo_fence_gate": 18,
    "minecraft:bamboo_slab": 18,
    "minecraft:bamboo_stairs": 18,
    "minecraft:bamboo_mosaic_slab": 18,
    "minecraft:bamboo_mosaic_stairs": 18,
    "minecraft:sponge": 18,
    "minecraft:wet_sponge": 18,
    "minecraft:hay_block": 18,
    "minecraft:horn_coral_block": 18,
    "minecraft:horn_coral": 18,
    "minecraft:horn_coral_fan": 18,
    "minecraft:bee_nest": 18,
    "minecraft:short_dry_grass": 18,
    "minecraft:tall_dry_grass": 18,
    "minecraft:wheat": 18,

    "minecraft:lime_wool": 19,
    "minecraft:lime_carpet": 19,
    "minecraft:lime_shulker_box": 19,
    "minecraft:lime_bed": 19,
    "minecraft:lime_stained_glass": 19,
    "minecraft:lime_glazed_terracotta": 19,
    "minecraft:lime_concrete": 19,
    "minecraft:lime_concrete_powder": 19,
    "minecraft:lime_candle": 19,
    "minecraft:melon": 19,

    "minecraft:pink_wool": 20,
    "minecraft:pink_carpet": 20,
    "minecraft:pink_shulker_box": 20,
    "minecraft:pink_bed": 20,
    "minecraft:pink_stained_glass": 20,
    "minecraft:pink_glazed_terracotta": 20,
    "minecraft:pink_concrete": 20,
    "minecraft:pink_concrete_powder": 20,
    "minecraft:pink_candle": 20,
    "minecraft:brain_coral_block": 20,
    "minecraft:brain_coral": 20,
    "minecraft:brain_coral_fan": 20,
    "minecraft:pearlescent_froglight": 20,
    "minecraft:cherry_leaves": 20,
    "minecraft:cherry_sapling": 20,
    "minecraft:cactus_flower": 20,

    "minecraft:gray_wool": 21,
    "minecraft:gray_carpet": 21,
    "minecraft:gray_shulker_box": 21,
    "minecraft:gray_bed": 21,
    "minecraft:gray_stained_glass": 21,
    "minecraft:gray_glazed_terracotta": 21,
    "minecraft:gray_concrete": 21,
    "minecraft:gray_concrete_powder": 21,
    "minecraft:gray_candle": 21,
    "minecraft:acacia_wood": 21,
    "minecraft:stripped_acacia_wood": 21,
    "minecraft:dead_tube_coral": 21,
    "minecraft:dead_tube_coral_fan": 21,
    "minecraft:dead_tube_coral_wall_fan": 21,
    "minecraft:dead_tube_coral_block": 21,
    "minecraft:dead_brain_coral": 21,
    "minecraft:dead_brain_coral_fan": 21,
    "minecraft:dead_brain_coral_wall_fan": 21,
    "minecraft:dead_brain_coral_block": 21,
    "minecraft:dead_bubble_coral": 21,
    "minecraft:dead_bubble_coral_fan": 21,
    "minecraft:dead_bubble_coral_wall_fan": 21,
    "minecraft:dead_bubble_coral_block": 21,
    "minecraft:dead_fire_coral": 21,
    "minecraft:dead_fire_coral_fan": 21,
    "minecraft:dead_fire_coral_wall_fan": 21,
    "minecraft:dead_fire_coral_block": 21,
    "minecraft:dead_horn_coral": 21,
    "minecraft:dead_horn_coral_fan": 21,
    "minecraft:dead_horn_coral_wall_fan": 21,
    "minecraft:dead_horn_coral_block": 21,
    "minecraft:tinted_glass": 21,
    "minecraft:dried_ghast": 21,
    "minecraft:light_gray_wool": 22,
    "minecraft:light_gray_carpet": 22,
    "minecraft:light_gray_shulker_box": 22,
    "minecraft:light_gray_bed": 22,
    "minecraft:light_gray_stained_glass": 22,
    "minecraft:light_gray_glazed_terracotta": 22,
    "minecraft:light_gray_concrete": 22,
    "minecraft:light_gray_concrete_powder": 22,
    "minecraft:light_gray_candle": 22,
    "minecraft:structure_block": 22,
    "minecraft:jigsaw": 22,
    "minecraft:pale_moss_carpet": 22,
    "minecraft:pale_moss_block": 22,
    "minecraft:test_block": 22,

    "minecraft:cyan_wool": 23,
    "minecraft:cyan_carpet": 23,
    "minecraft:cyan_shulker_box": 23,
    "minecraft:cyan_bed": 23,
    "minecraft:cyan_stained_glass": 23,
    "minecraft:cyan_glazed_terracotta": 23,
    "minecraft:cyan_concrete": 23,
    "minecraft:cyan_concrete_powder": 23,
    "minecraft:cyan_candle": 23,
    "minecraft:prismarine_slab": 23,
    "minecraft:prismarine_stairs": 23,
    "minecraft:prismarine_wall": 23,
    "minecraft:warped_roots": 23,
    "minecraft:warped_fungus": 23,
    "minecraft:twisting_vines": 23,
    "minecraft:nether_sprouts": 23,
    "minecraft:sculk_sensor": 23,
    "minecraft:calibrated_sculk_sensor": 23,
    "minecraft:warped_pressure_plate": 23,
    "minecraft:warped_sign": 23,
    "minecraft:warped_wall_sign": 23,
    "minecraft:warped_slab": 23,
    "minecraft:warped_trapdoor": 23,
    "minecraft:warped_fence": 23,
    "minecraft:prismarine": 23,

    "minecraft:purple_shulker_box": 24,
    "minecraft:purple_wool": 24,
    "minecraft:purple_carpet": 24,
    "minecraft:purple_bed": 24,
    "minecraft:purple_stained_glass": 24,
    "minecraft:purple_glazed_terracotta": 24,
    "minecraft:purple_concrete": 24,
    "minecraft:purple_concrete_powder": 24,
    "minecraft:purple_candle": 24,
    "minecraft:mycelium": 24,
    "minecraft:chorus_plant": 24,
    "minecraft:chorus_flower": 24,
    "minecraft:repeating_command_block": 24,
    "minecraft:bubble_coral_block": 24,
    "minecraft:bubble_coral": 24,
    "minecraft:bubble_coral_fan": 24,
    "minecraft:amethyst_block": 24,
    "minecraft:budding_amethyst": 24,
    "minecraft:amethyst_cluster": 24,
    "minecraft:small_amethyst_bud": 24,
    "minecraft:medium_amethyst_bud": 24,
    "minecraft:large_amethyst_bud": 24,

    "minecraft:blue_wool": 25,
    "minecraft:blue_carpet": 25,
    "minecraft:blue_shulker_box": 25,
    "minecraft:blue_bed": 25,
    "minecraft:blue_stained_glass": 25,
    "minecraft:blue_glazed_terracotta": 25,
    "minecraft:blue_concrete": 25,
    "minecraft:blue_concrete_powder": 25,
    "minecraft:blue_candle": 25,
    "minecraft:tube_coral_block": 25,
    "minecraft:tube_coral": 25,
    "minecraft:tube_coral_fan": 25,

    "minecraft:brown_wool": 26,
    "minecraft:brown_carpet": 26,
    "minecraft:brown_shulker_box": 26,
    "minecraft:brown_bed": 26,
    "minecraft:brown_stained_glass": 26,
    "minecraft:brown_glazed_terracotta": 26,
    "minecraft:brown_concrete": 26,
    "minecraft:brown_concrete_powder": 26,
    "minecraft:brown_candle": 26,
    "minecraft:dark_oak_planks": 26,
    "minecraft:dark_oak_log": 26,
    "minecraft:stripped_dark_oak_log": 26,
    "minecraft:dark_oak_wood": 26,
    "minecraft:stripped_dark_oak_wood": 26,
    "minecraft:dark_oak_sign": 26,
    "minecraft:dark_oak_wall_sign": 26,
    "minecraft:dark_oak_pressure_plate": 26,
    "minecraft:dark_oak_trapdoor": 26,
    "minecraft:dark_oak_stairs": 26,
    "minecraft:dark_oak_slab": 26,
    "minecraft:dark_oak_fence_gate": 26,
    "minecraft:dark_oak_fence": 26,
    "minecraft:dark_oak_door": 26,
    "minecraft:spruce_log": 26,
    "minecraft:soul_sand": 26,
    "minecraft:command_block": 26,
    "minecraft:brown_mushroom": 26,
    "minecraft:soul_soil": 26,
    "minecraft:leaf_litter": 26,

    "minecraft:green_wool": 27,
    "minecraft:green_carpet": 27,
    "minecraft:green_shulker_box": 27,
    "minecraft:green_bed": 27,
    "minecraft:green_stained_glass": 27,
    "minecraft:green_glazed_terracotta": 27,
    "minecraft:green_concrete": 27,
    "minecraft:green_concrete_powder": 27,
    "minecraft:green_candle": 27,
    "minecraft:end_portal_frame": 27,
    "minecraft:chain_command_block": 27,
    "minecraft:sea_pickle": 27,
    "minecraft:moss_carpet": 27,
    "minecraft:moss_block": 27,
    "minecraft:dried_kelp_block": 27,

    "minecraft:red_wool": 28,
    "minecraft:red_carpet": 28,
    "minecraft:red_shulker_box": 28,
    "minecraft:red_bed": 28,
    "minecraft:red_stained_glass": 28,
    "minecraft:red_glazed_terracotta": 28,
    "minecraft:red_concrete": 28,
    "minecraft:red_concrete_powder": 28,
    "minecraft:red_candle": 28,
    "minecraft:bricks": 28,
    "minecraft:brick_slab": 28,
    "minecraft:brick_stairs": 28,
    "minecraft:brick_wall": 28,
    "minecraft:red_mushroom_block": 28,
    "minecraft:nether_wart": 28,
    "minecraft:enchanting_table": 28,
    "minecraft:nether_wart_block": 28,
    "minecraft:fire_coral_block": 28,
    "minecraft:fire_coral": 28,
    "minecraft:fire_coral_fan": 28,
    "minecraft:red_mushroom": 28,
    "minecraft:shroomlight": 28,
    "minecraft:mangrove_planks": 28,
    "minecraft:mangrove_log": 28,
    "minecraft:stripped_mangrove_log": 28,
    "minecraft:mangrove_wood": 28,
    "minecraft:stripped_mangrove_wood": 28,
    "minecraft:mangrove_sign": 28,
    "minecraft:mangrove_wall_sign": 28,
    "minecraft:mangrove_door": 28,
    "minecraft:mangrove_pressure_plate": 28,
    "minecraft:mangrove_fence": 28,
    "minecraft:mangrove_trapdoor": 28,
    "minecraft:mangrove_fence_gate": 28,
    "minecraft:mangrove_slab": 28,
    "minecraft:mangrove_stairs": 28,
    "minecraft:sniffer_egg": 28,

    "minecraft:black_wool": 29,
    "minecraft:black_carpet": 29,
    "minecraft:black_shulker_box": 29,
    "minecraft:black_bed": 29,
    "minecraft:black_stained_glass": 29,
    "minecraft:black_glazed_terracotta": 29,
    "minecraft:black_concrete": 29,
    "minecraft:black_concrete_powder": 29,
    "minecraft:black_candle": 29,
    "minecraft:obsidian": 29,
    "minecraft:end_portal": 29,
    "minecraft:dragon_egg": 29,
    "minecraft:coal_block": 29,
    "minecraft:end_gateway": 29,
    "minecraft:basalt": 29,
    "minecraft:polished_basalt": 29,
    "minecraft:smooth_basalt": 29,
    "minecraft:netherite_block": 29,
    "minecraft:ancient_debris": 29,
    "minecraft:crying_obsidian": 29,
    "minecraft:respawn_anchor": 29,
    "minecraft:blackstone": 29,
    "minecraft:polished_blackstone": 29,
    "minecraft:polished_blackstone_bricks": 29,
    "minecraft:blackstone_slab": 29,
    "minecraft:blackstone_stairs": 29,
    "minecraft:blackstone_wall": 29,
    "minecraft:polished_blackstone_slab": 29,
    "minecraft:polished_blackstone_stairs": 29,
    "minecraft:polished_blackstone_wall": 29,
    "minecraft:polished_blackstone_brick_slab": 29,
    "minecraft:polished_blackstone_brick_stairs": 29,
    "minecraft:polished_blackstone_brick_wall": 29,
    "minecraft:gilded_blackstone": 29,
    "minecraft:chiseled_polished_blackstone": 29,
    "minecraft:cracked_polished_blackstone_bricks": 29,
    "minecraft:polished_blackstone_button": 29,
    "minecraft:polished_blackstone_pressure_plate": 29,
    "minecraft:sculk": 29,
    "minecraft:sculk_vein": 29,
    "minecraft:sculk_catalyst": 29,
    "minecraft:sculk_shrieker": 29,
    "minecraft:sculk_sensor": 29,

    "minecraft:gold_block": 30,
    "minecraft:light_weighted_pressure_plate": 30,
    "minecraft:bell": 30,
    "minecraft:raw_gold_block": 30,

    "minecraft:diamond_block": 31,
    "minecraft:beacon": 31,
    "minecraft:prismarine_bricks": 31,
    "minecraft:prismarine_brick_slab": 31,
    "minecraft:prismarine_brick_stairs": 31,
    "minecraft:dark_prismarine_slab": 31,
    "minecraft:dark_prismarine_stairs": 31,
    "minecraft:conduit": 31,

    "minecraft:lapis_block": 32,

    "minecraft:emerald_block": 33,

    "minecraft:podzol": 34,
    "minecraft:spruce_planks": 34,
    "minecraft:spruce_log": 34,
    "minecraft:stripped_spruce_log": 34,
    "minecraft:spruce_wood": 34,
    "minecraft:stripped_spruce_wood": 34,
    "minecraft:spruce_sign": 34,
    "minecraft:spruce_wall_sign": 34,
    "minecraft:spruce_pressure_plate": 34,
    "minecraft:spruce_trapdoor": 34,
    "minecraft:spruce_stairs": 34,
    "minecraft:spruce_slab": 34,
    "minecraft:spruce_fence_gate": 34,
    "minecraft:spruce_fence": 34,
    "minecraft:spruce_door": 34,
    "minecraft:oak_log": 34,
    "minecraft:jungle_log": 34,
    "minecraft:campfire": 34,
    "minecraft:soul_campfire": 34,
    "minecraft:mangrove_log": 34,
    "minecraft:mangrove_roots": 34,
    "minecraft:muddy_mangrove_roots": 34,

    "minecraft:netherrack": 35,
    "minecraft:nether_brick_fence": 35,
    "minecraft:nether_brick_slab": 35,
    "minecraft:nether_brick_stairs": 35,
    "minecraft:nether_brick_wall": 35,
    "minecraft:chiseled_nether_bricks": 35,
    "minecraft:cracked_nether_bricks": 35,
    "minecraft:nether_gold_ore": 35,
    "minecraft:nether_quartz_ore": 35,
    "minecraft:magma_block": 35,
    "minecraft:red_nether_bricks": 35,
    "minecraft:red_nether_brick_slab": 35,
    "minecraft:red_nether_brick_stairs": 35,
    "minecraft:red_nether_brick_wall": 35,
    "minecraft:crimson_roots": 35,
    "minecraft:crimson_fungus": 35,
    "minecraft:weeping_vines": 35,
    "minecraft:crimson_pressure_plate": 35,
    "minecraft:crimson_sign": 35,
    "minecraft:crimson_wall_sign": 35,
    "minecraft:crimson_slab": 35,
    "minecraft:crimson_trapdoor": 35,
    "minecraft:crimson_fence": 35,

    "minecraft:white_terracotta": 36,
    "minecraft:calcite": 36,
    "minecraft:cherry_planks": 36,
    "minecraft:cherry_log": 36,
    "minecraft:stripped_cherry_log": 36,
    "minecraft:cherry_sign": 36,
    "minecraft:cherry_wall_sign": 36,
    "minecraft:cherry_pressure_plate": 36,
    "minecraft:cherry_trapdoor": 36,
    "minecraft:cherry_stairs": 36,
    "minecraft:cherry_slab": 36,
    "minecraft:cherry_fence_gate": 36,
    "minecraft:cherry_fence": 36,
    "minecraft:cherry_door": 36,

    "minecraft:orange_terracotta": 37,
    "minecraft:redstone_lamp": 37,
    "minecraft:resin_brick_fence": 37,
    "minecraft:resin_brick_slab": 37,
    "minecraft:resin_brick_stairs": 37,
    "minecraft:resin_brick_wall": 37,
    "minecraft:chiseled_resin_bricks": 37,
    "minecraft:resin_block": 37,
    "minecraft:resin_clump": 37,

    "minecraft:magenta_terracotta": 38,

    "minecraft:light_blue_terracotta": 39,

    "minecraft:yellow_terracotta": 40,

    "minecraft:lime_terracotta": 41,

    "minecraft:pink_terracotta": 42,
    "minecraft:stripped_cherry_log": 42,
    "minecraft:stripped_cherry_wood": 42,

    "minecraft:gray_terracotta": 43,
    "minecraft:cherry_log": 43,
    "minecraft:cherry_wood": 43,
    "minecraft:tuff": 43,
    "minecraft:tuff_slab": 43,
    "minecraft:tuff_stairs": 43,
    "minecraft:tuff_wall": 43,
    "minecraft:polished_tuff": 43,
    "minecraft:polished_tuff_slab": 43,
    "minecraft:polished_tuff_stairs": 43,
    "minecraft:polished_tuff_wall": 43,
    "minecraft:tuff_bricks": 43,
    "minecraft:tuff_brick_slab": 43,
    "minecraft:tuff_brick_stairs": 43,
    "minecraft:tuff_brick_wall": 43,
    "minecraft:chiseled_tuff": 43,
    "minecraft:chiseled_tuff_bricks": 43,

    "minecraft:light_gray_terracotta": 44,
    "minecraft:exposed_copper": 44,
    "minecraft:exposed_cut_copper": 44,
    "minecraft:exposed_cut_copper_slab": 44,
    "minecraft:exposed_cut_copper_stairs": 44,
    "minecraft:exposed_copper_trapdoor": 44,
    "minecraft:waxed_exposed_copper": 44,
    "minecraft:waxed_exposed_cut_copper": 44,
    "minecraft:waxed_exposed_cut_copper_slab": 44,
    "minecraft:waxed_exposed_cut_copper_stairs": 44,
    "minecraft:waxed_exposed_copper_trapdoor": 44,
    "minecraft:mud_bricks": 44,
    "minecraft:mud_brick_slab": 44,
    "minecraft:mud_brick_stairs": 44,
    "minecraft:mud_brick_wall": 44,

    "minecraft:cyan_terracotta": 45,
    "minecraft:mud": 45,

    "minecraft:purple_terracotta": 46,
    "minecraft:shulker_box": 46,

    "minecraft:blue_terracotta": 47,

    "minecraft:brown_terracotta": 48,
    "minecraft:pointed_dripstone": 48,
    "minecraft:dripstone_block": 48,

    "minecraft:green_terracotta": 49,

    "minecraft:red_terracotta": 50,
    "minecraft:decorated_pot": 50,

    "minecraft:black_terracotta": 51,

    "minecraft:crimson_nylium": 52,

    "minecraft:crimson_door": 53,
    "minecraft:crimson_stairs": 53,
    "minecraft:crimson_stem": 53,
    "minecraft:stripped_crimson_stem": 53,
    "minecraft:crimson_fence_gate": 53,
    "minecraft:crimson_planks": 53,
    "minecraft:crimson_pressure_plate": 53,
    "minecraft:crimson_sign": 53,
    "minecraft:crimson_wall_sign": 53,
    "minecraft:crimson_slab": 53,
    "minecraft:crimson_trapdoor": 53,
    "minecraft:crimson_fence": 53,

    "minecraft:crimson_hyphae": 54,
    "minecraft:stripped_crimson_hyphae": 54,

    "minecraft:warped_nylium": 55,
    "minecraft:oxidized_copper": 55,
    "minecraft:oxidized_cut_copper": 55,
    "minecraft:oxidized_cut_copper_slab": 55,
    "minecraft:oxidized_cut_copper_stairs": 55,
    "minecraft:oxidized_copper_trapdoor": 55,
    "minecraft:waxed_oxidized_copper": 55,
    "minecraft:waxed_oxidized_cut_copper": 55,
    "minecraft:waxed_oxidized_cut_copper_slab": 55,
    "minecraft:waxed_oxidized_cut_copper_stairs": 55,
    "minecraft:waxed_oxidized_copper_trapdoor": 55,

    "minecraft:warped_door": 56,
    "minecraft:warped_stairs": 56,
    "minecraft:warped_stem": 56,
    "minecraft:stripped_warped_stem": 56,
    "minecraft:warped_fence_gate": 56,
    "minecraft:warped_planks": 56,
    "minecraft:warped_slab": 56,
    "minecraft:warped_pressure_plate": 56,
    "minecraft:warped_sign": 56,
    "minecraft:warped_wall_sign": 56,
    "minecraft:warped_trapdoor": 56,
    "minecraft:warped_fence": 56,
    "minecraft:weathered_copper": 56,
    "minecraft:weathered_cut_copper": 56,
    "minecraft:weathered_cut_copper_slab": 56,
    "minecraft:weathered_cut_copper_stairs": 56,
    "minecraft:weathered_copper_trapdoor": 56,
    "minecraft:waxed_weathered_copper": 56,
    "minecraft:waxed_weathered_cut_copper": 56,
    "minecraft:waxed_weathered_cut_copper_slab": 56,
    "minecraft:waxed_weathered_cut_copper_stairs": 56,
    "minecraft:waxed_weathered_copper_trapdoor": 56,

    "minecraft:warped_hyphae": 57,
    "minecraft:stripped_warped_hyphae": 57,

    "minecraft:warped_wart_block": 58,

    "minecraft:deepslate_gold_ore": 59,
    "minecraft:deepslate_iron_ore": 59,
    "minecraft:deepslate_coal_ore": 59,
    "minecraft:deepslate_lapis_ore": 59,
    "minecraft:deepslate_diamond_ore": 59,
    "minecraft:deepslate_redstone_ore": 59,
    "minecraft:deepslate_emerald_ore": 59,
    "minecraft:deepslate_copper_ore": 59,
    "minecraft:deepslate": 59,
    "minecraft:cobbled_deepslate": 59,
    "minecraft:polished_deepslate": 59,
    "minecraft:deepslate_bricks": 59,
    "minecraft:deepslate_tiles": 59,
    "minecraft:chiseled_deepslate": 59,
    "minecraft:cobbled_deepslate_stairs": 59,
    "minecraft:cobbled_deepslate_slab": 59,
    "minecraft:cobbled_deepslate_wall": 59,
    "minecraft:polished_deepslate_stairs": 59,
    "minecraft:polished_deepslate_slab": 59,
    "minecraft:polished_deepslate_wall": 59,
    "minecraft:deepslate_brick_stairs": 59,
    "minecraft:deepslate_brick_slab": 59,
    "minecraft:deepslate_brick_wall": 59,
    "minecraft:deepslate_tile_stairs": 59,
    "minecraft:deepslate_tile_slab": 59,
    "minecraft:deepslate_tile_wall": 59,
    "minecraft:infested_deepslate": 59,
    "minecraft:reinforced_deepslate": 59,

    "minecraft:raw_iron_block": 60,

    "minecraft:glow_lichen": 61,
    "minecraft:verdant_froglight": 61,
}
